### ISSUE TITLE
I not run this project in my android studios please help me this project domain is my last year project so please help me

### ISSUE THREAD

**Issue by Rajesh4920** [bhavya092/Sahara#1]

**Comment by bhavya092** [comment]
Hello Rajesh ! 
This is a project based on Flutter framework using Dart language. You need to have these installed in your local machine with an enabled emulator SDK on Android Studio. Also for the Google Firebase part, you need to add your own authentication keys.
The code might have some version conflicts that you should resolve prior to the execution of the code. If these things are done perfectly and proper environment variables are set, I guess the code must work.
Thank you.
